### ISSUE TITLE
update to new version 13.2

### ISSUE THREAD

**Issue by TheLeftMoose** [itzg/docker-rcon-web-admin#1]
It seems like dockerhub don't detect when upstream releases a new zip file. Would it be possible to force build a new version of this repo on dockerhub. 

Maybe setup somekind of way to detect new version upstream?

thanks in advance.

**Comment by itzg** [comment]
Yeah, dockerhub can only be auto-triggered by github activity. I manually triggered a build and now the latest image contains 0.13.2:

![image](https://user-images.githubusercontent.com/988985/37904927-d08d529a-30c2-11e8-93ad-563b0de933b0.png)

**Comment by itzg** [comment]
...BTW, thank you for reporting this :)
