### ISSUE TITLE
Switch to @lacaulac's fork

### ISSUE THREAD

**Issue by ChipWolf** [itzg/docker-rcon-web-admin#4]
@brainfoolong has discontinued the project, it was handed over to @lacaulac

I reckon it may be a good idea to pull down and maintain a downstream fork of lacaulac's code specifically for this container. This would be ideal for implementing environment variable configuration options, for example.

**Comment by itzg** [comment]
Yep, I was waiting for the go ahead from @lacaulac . Ready for the switch?

**Comment by lacaulac** [comment]
Hey! Well, due to my bad habit of piling up gazillions on side projects there hasn't been much movement on rcon-web-admin since I first contacted @itzg. On a side note, @kdog31 also made a Dockerfile that's pulling from my fork (https://github.com/kdog31/rcon).
As for what to do, I must say that I'm not quite sure since apparently @itzg 's docker repository is still working with the old version. As far as I remember, the main change I made was updating some node modules that were presenting vulnerabilities in their past versions, so it might be a good idea to move to that version, but at the same time @brainfoolong 's version seems to be the most stable.

**Comment by itzg** [comment]
I totally understand the scenario :)

That sounds like a pretty low risk update, so sounds I could tag the current image build point and switch over from there very safely.

**Comment by itzg** [comment]
...oh, @lacaulac I'll need you to cut a new release at https://github.com/lacaulac/rcon-web-admin/releases since the Dockerfile pulls from there

https://github.com/itzg/docker-rcon-web-admin/blob/e1d5aea0f49fe2cfabf1844cc2627a93ac79b16e/Dockerfile#L7-L9

**Comment by lacaulac** [comment]
Thank you for understanding! I published a new release, under the version 0.14.
https://github.com/lacaulac/rcon-web-admin/releases/tag/0.14

**Comment by kdog31** [comment]
@itzg there is a key difference between your container and mine, yours is pulling specific versions, mine is pulling from master. @lacaulac i feel this could be useful info for you if you wanted to involve docker as part of your development process. I will modify my Jenkins pipeline to watch for changes on your repository and trigger a new build.

**Comment by lacaulac** [comment]
@kdog31 Aw, yes, I must say I didn't remember this specific detail. That could indeed prove useful on order to "test" in a clean environment as I see it. Unless I'm missing something else?

**Comment by kdog31** [comment]
@lacaulac thats pretty much exactly how i build with docker. You may just need to not use the cached images '--force-recreate' if using docker compose or '--no-cache' if using building the container locally (which i would recommend if you are rapidly changing, building, testing)

**Comment by ChipWolf** [comment]
I'll be pushing some working changes to the application code for environment variable configuration here https://github.com/ChipWolf/rcon-web-admin I'll be creating a PR to merge it into @lacaulac's upstream once it's in a good state

**Comment by lacaulac** [comment]
@kdog31 Alright, thank you for the information (I'm not that much of a Docker content creator as you might have figured)
@ChipWolf Sounds great, thank you for participating in the project!

**Comment by ChipWolf** [comment]
PR to support basic setup of a user and a server: https://github.com/lacaulac/rcon-web-admin/pull/1

**Comment by itzg** [comment]
@kdog31 you appear to have "forked" my repo without providing any indication of the derivation. You also did not bring over the license file, https://github.com/itzg/docker-rcon-web-admin/blob/master/LICENSE, where MIT is pretty simple but does state:

> A short and simple permissive license with conditions only requiring preservation of copyright and license notices

**Comment by itzg** [comment]
@lacaulac @ChipWolf , I have pushed an update of the Dockerfile which now pulls from the new location and the image is available in Docker Hub.

**Comment by itzg** [comment]
...and BTW, `RCON_WEB_ADMIN_VERSION` is purposely a build argument so that one can locally build against master by using:

```
docker build --build-arg RCON_WEB_ADMIN_VERSION=master .
```

**Comment by ChipWolf** [comment]
@itzg the upstream has moved to rcon-web-admin/rcon-web-admin

**Comment by itzg** [comment]
Quite the moving target ;) Latest image has now switched to rcon-web-admin org
