### ISSUE TITLE
Node version discrepancy

### ISSUE THREAD

**Issue by jabbink** [itzg/docker-rcon-web-admin#5]
Not that I noticed any issues with the image, but I noticed you use `node:10` even though the upstream requirements state to use atleast `node:12.13.1` https://github.com/rcon-web-admin/rcon-web-admin#requirements

Any reason for the choice of Node 10?

**Comment by itzg** [comment]
I don't remember any particular reason. I'm thinking that might have been the nodejs version at the time when first integrating. I'll double check that it works fine with `node:12` or `node:12.18` since that's the latest of the LTS version.

**Comment by itzg** [comment]
Latest image is now based on 12.18 (or `12` specifically)
